// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_eGV8uSKmN5CtxZuzNL7fb_i_oArMa4',
    appId: '1:758621203820:web:a37b75dc6a1728ceb5d749',
    messagingSenderId: '758621203820',
    projectId: 'sharpcut-notification',
    authDomain: 'sharpcut-notification.firebaseapp.com',
    storageBucket: 'sharpcut-notification.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKuMm7TfaTy-ZpvawjuM_vX2JHevsiBDg',
    appId: '1:758621203820:android:53f294611d3a1054b5d749',
    messagingSenderId: '758621203820',
    projectId: 'sharpcut-notification',
    storageBucket: 'sharpcut-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgO1vkBnIauVKzWYZ871ZVQ0sxXUdDuck',
    appId: '1:758621203820:ios:0a9580d52fa8517ab5d749',
    messagingSenderId: '758621203820',
    projectId: 'sharpcut-notification',
    storageBucket: 'sharpcut-notification.firebasestorage.app',
    iosBundleId: 'com.example.sharpCut',
  );
}
